### ISSUE TITLE
etree was removed lxml

### ISSUE THREAD

**Issue by Jokky6** [Ayrx/binja-JNIAnalyzer#1]
when python>3.5,etree can not found in lxml.
so, `from lxml import etree` will error!
please fix.

**Comment by Ayrx** [comment]
How did you install the plugin? 

`lxml` is a third party dependency that needs to be installed. If the plugin is installed via the plugin manager, dependencies should be automatically installed. Otherwise, `pip install` the dependencies listed in the `requirements.txt` file.
